# Generated by Django 3.1.7 on 2021-04-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'Unico': 'Ya existe un usuario con esa dirección de Email.'}, max_length=254, unique=True)),
                ('full_name', models.CharField(help_text='Nombre completo', max_length=50, verbose_name='Nombre y Apellido')),
                ('phone', models.CharField(blank=True, help_text='Numero de Teléfono del usuario', max_length=17, verbose_name='Numero de Teléfono')),
                ('library', models.ForeignKey(help_text='Libreria del Usuario', on_delete=django.db.models.deletion.CASCADE, to='book.library', verbose_name='Libreria')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('libraries', models.ManyToManyField(to='book.Library')),
            ],
        ),
    ]
