# Generated by Django 3.1.7 on 2021-04-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'Unico': 'Ya existe un usuario con esa dirección de Email.'}, max_length=254, unique=True)),
                ('full_name', models.CharField(help_text='Nombre completo', max_length=50, verbose_name='Nombre y Apellido')),
                ('phone', models.CharField(blank=True, help_text='Numero de Teléfono del usuario', max_length=17, verbose_name='Numero de Teléfono')),
                ('library', models.ForeignKey(help_text='Libreria del Usuario', on_delete=django.db.models.deletion.CASCADE, to='book.library', verbose_name='Libreria')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
