# Generated by Django 3.1.7 on 2021-04-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_leads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
    ]
